apiVersion: apps/v1
kind: Deployment
metadata:
  name: tada-api-staging
  namespace: tada-staging
  labels:
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: tada-api-staging
  template:
    metadata:
      labels:
        name: tada-api-staging
    spec:
      containers:
        - name: tada-api
          image: 950066988925.dkr.ecr.ap-southeast-1.amazonaws.com/tada-api:stag
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-registry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
---
apiVersion: v1
kind: Service
metadata:
  name: tada-api-staging
  namespace: tada-staging
  labels:
    type: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    name: tada-api-staging
